In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Salaries.csv")

In [12]:
df.head() # To set the upper part of our dataset

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [13]:
df.columns # to check columns value

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [26]:
df.shape

(51, 6)

In [17]:
df.columns.value_counts() #To check how many columns is there

rank          1
discipline    1
phd           1
service       1
sex           1
salary        1
Name: count, dtype: int64

In [6]:
df.dtypes # to check datatype

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [ ]:
df.tail(10) # to check down data of our dataset we are using tail

         rank discipline  phd  service     sex  salary
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [ ]:
df.describe() # it will give all all agregate things like mean,median, mode and quater also.

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [18]:
df.max()

rank            Prof
discipline         B
phd               56
service           49
sex             Male
salary        186960
dtype: object

In [19]:
df.min()

rank          AssocProf
discipline            A
phd                   1
service               0
sex              Female
salary            63100
dtype: object

In [8]:
df.mean() # it is giving error because in out dataset object value is also there so that its giving error

TypeError: Could not convert ['ProfProfAssocProfProfAsstProfProfAsstProfAsstProfProfProfAsstProfProfAsstProfAsstProfProfAsstProfProfAssocProfProfAssocProfProfAsstProfProfAssocProfProfAsstProfAssocProfProfAsstProfProfProfAsstProfAsstProfProfAssocProfAsstProfProfAssocProfProfAsstProfProfAsstProfProfAsstProfAssocProfProfProfAssocProfProfProfProf'
 'BAABBBBBAABAAAABBBBBBBAABBBBBBAAABBBAAAAAAAABBBBBAA'
 'MaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemale'] to numeric

In [ ]:
df.discipline.value_counts() # how many times diffrent items came

B    42
A    36
Name: discipline, dtype: int64

In [20]:
df.describe()

             phd    service         salary
count  51.000000  51.000000      51.000000
mean   17.705882  12.960784  106278.568627
std    12.090152  11.615439   27957.854794
min     1.000000   0.000000   63100.000000
25%     8.000000   3.000000   86500.000000
50%    17.000000  10.000000  103994.000000
75%    24.500000  20.000000  123041.500000
max    56.000000  49.000000  186960.000000

In [27]:
df.std()

TypeError: could not convert string to float: 'Prof'

In [9]:
df_50=df.head(50)

In [10]:
df_50.mean()

TypeError: Could not convert ['ProfProfAssocProfProfAsstProfProfAsstProfAsstProfProfProfAsstProfProfAsstProfAsstProfProfAsstProfProfAssocProfProfAssocProfProfAsstProfProfAssocProfProfAsstProfAssocProfProfAsstProfProfProfAsstProfAsstProfProfAssocProfAsstProfProfAssocProfProfAsstProfProfAsstProfProfAsstProfAssocProfProfProfAssocProfProfProf'
 'BAABBBBBAABAAAABBBBBBBAABBBBBBAAABBBAAAAAAAABBBBBA'
 'MaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemale'] to numeric

In [11]:
df.head(50).mean()

TypeError: Could not convert ['ProfProfAssocProfProfAsstProfProfAsstProfAsstProfProfProfAsstProfProfAsstProfAsstProfProfAsstProfProfAssocProfProfAssocProfProfAsstProfProfAssocProfProfAsstProfAssocProfProfAsstProfProfProfAsstProfAsstProfProfAssocProfAsstProfProfAssocProfProfAsstProfProfAsstProfProfAsstProfAssocProfProfProfAssocProfProfProf'
 'BAABBBBBAABAAAABBBBBBBAABBBBBBAAABBBAAAAAAAABBBBBA'
 'MaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleMaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemaleFemale'] to numeric

In [22]:
#Selecting a column
df.salary

0     186960
1     122400
2      81285
3     134778
4      88000
5     150480
6      75044
7      92000
8     107300
9     150500
10     92000
11    103106
12     73000
13     85000
14     91100
15     91300
16    123683
17    107008
18    155750
19    119800
20    146856
21     91000
22    137000
23     74830
24    140096
25     74692
26    103613
27    111512
28     97032
29    127512
30    105000
31     73500
32     72500
33    144651
34    103994
35     92000
36     91000
37     73300
38    117555
39     63100
40     90450
41     77500
42    116450
43     78500
44     71065
45    161101
46    105450
47    104542
48    124312
49    109954
50    109646
Name: salary, dtype: int64

In [23]:
df['salary'] #its a single dimession column

0     186960
1     122400
2      81285
3     134778
4      88000
5     150480
6      75044
7      92000
8     107300
9     150500
10     92000
11    103106
12     73000
13     85000
14     91100
15     91300
16    123683
17    107008
18    155750
19    119800
20    146856
21     91000
22    137000
23     74830
24    140096
25     74692
26    103613
27    111512
28     97032
29    127512
30    105000
31     73500
32     72500
33    144651
34    103994
35     92000
36     91000
37     73300
38    117555
39     63100
40     90450
41     77500
42    116450
43     78500
44     71065
45    161101
46    105450
47    104542
48    124312
49    109954
50    109646
Name: salary, dtype: int64

In [ ]:
df[['salary']] # throgh double sqare bracket we are converting it into 2d

    salary
0   186960
1    93000
2   110515
3   131205
4   104800
..     ...
73  105450
74  104542
75  124312
76  109954
77  109646

[78 rows x 1 columns]

In [24]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [25]:
df.shape

(51, 6)

Calculate the basic statistics for the Phd column;

Find how many values in the Phd column (use count method);

Calculate the average Phd;

In [ ]:
df.phd.describe()

count    78.000000
mean     19.705128
std      12.498425
min       1.000000
25%      10.250000
50%      18.500000
75%      27.750000
max      56.000000
Name: phd, dtype: float64

In [ ]:
df.phd.count()

78

In [ ]:
df.phd.mean()

19.705128205128204

In [ ]:
df.groupby(['rank']).mean()

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [ ]:
df.groupby('rank')[['salary','phd']].mean() # through groupby in single line we can find min,median and mode and everything

                  salary        phd
rank
AssocProf   91786.230769  15.076923
AsstProf    81362.789474   5.052632
Prof       123624.804348  27.065217

In [ ]:
grouped=df.groupby('rank')

In [ ]:
type(grouped)

pandas.core.groupby.generic.DataFrameGroupBy

In [28]:
df[df.salary>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   20       20    Male  122400
3   Prof          B   23       23    Male  134778
5   Prof          B   17        3    Male  150480
9   Prof          A   29       27    Male  150500
16  Prof          B   21       20    Male  123683
18  Prof          B   22       21    Male  155750
20  Prof          B   45       45    Male  146856
22  Prof          A   39       36  Female  137000
24  Prof          B   25       25  Female  140096
29  Prof          B   20       14  Female  127512
33  Prof          B   36       26  Female  144651
45  Prof          B   24       15  Female  161101
48  Prof          B   17       17  Female  124312

In [29]:
df_sub= [df.salary > 120000]

In [ ]:
df_sub

[0      True
 1      True
 2     False
 3      True
 4     False
 5      True
 6     False
 7     False
 8     False
 9      True
 10    False
 11    False
 12    False
 13    False
 14    False
 15    False
 16     True
 17    False
 18     True
 19    False
 20     True
 21    False
 22     True
 23    False
 24     True
 25    False
 26    False
 27    False
 28    False
 29     True
 30    False
 31    False
 32    False
 33     True
 34    False
 35    False
 36    False
 37    False
 38    False
 39    False
 40    False
 41    False
 42    False
 43    False
 44    False
 45     True
 46    False
 47    False
 48     True
 49    False
 50    False
 Name: salary, dtype: bool]

In [ ]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [ ]:
df.iloc[1:4, 0:3]

   rank discipline  phd
1  Prof          A   12
2  Prof          A   23
3  Prof          A   40

In [ ]:
df.iloc[0:10,0:3]

        rank discipline  phd
0       Prof          B   56
1       Prof          A   12
2       Prof          A   23
3       Prof          A   40
4       Prof          B   20
5       Prof          A   20
6  AssocProf          A   20
7       Prof          A   18
8       Prof          A   29
9       Prof          A   51

In [ ]:
df.iloc[0:2,]

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000

In [ ]:
df.iloc[:,4]

0       Male
1       Male
2       Male
3       Male
4       Male
       ...
73    Female
74    Female
75    Female
76    Female
77    Female
Name: sex, Length: 78, dtype: object